
from __future__ import annotations
import ast, hashlib, json, operator, subprocess, sys
from pathlib import Path
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field

app = FastAPI(title="FICA–IGF-U Platform", version="1.0.5")

BINOPS={ast.Add:operator.add,ast.Sub:operator.sub,ast.Mult:operator.mul,
        ast.FloorDiv:operator.floordiv,ast.Mod:operator.mod}

def safe_eval(expr:str)->int:
    tree=ast.parse(expr,mode="eval")
    def v(n):
        if isinstance(n,ast.Expression): return v(n.body)
        if isinstance(n,ast.Constant) and type(n.value) is int: return n.value
        if isinstance(n,ast.UnaryOp) and isinstance(n.op,(ast.UAdd,ast.USub)):
            x=v(n.operand); return x if isinstance(n.op,ast.UAdd) else -x
        if isinstance(n,ast.BinOp) and type(n.op) in BINOPS:
            a,b=v(n.left),v(n.right)
            if isinstance(n.op,(ast.FloorDiv,ast.Mod)) and b==0: raise ValueError("division by zero")
            return BINOPS[type(n.op)](a,b)
        raise ValueError("unsupported expression")
    return v(tree)

DOMAINS = {
    "integer": "Exact integer states and arithmetic",
    "modular": "Residue-class computations",
    "sequence": "Ordered finite trajectories",
    "symbolic": "Restricted exact integer expressions",
    "relation": "Predicates over computed objects",
}

OPERATORS = {
    "add": {"domain": "integer", "arity": 2},
    "subtract": {"domain": "integer", "arity": 2},
    "multiply": {"domain": "integer", "arity": 2},
    "divide_floor": {"domain": "integer", "arity": 2},
    "modulo": {"domain": "integer", "arity": 2},
    "add_mod": {"domain": "modular", "arity": 3},
    "multiply_mod": {"domain": "modular", "arity": 3},
    "collatz_step": {"domain": "integer", "arity": 1},
}

DEFINITIONS = [
    {"id":"D001","statement":"A state is a machine-readable mathematical object with an explicit domain."},
    {"id":"D002","statement":"An operator is a registered transformation with explicit domain and arity."},
    {"id":"D003","statement":"A trajectory is an ordered sequence generated by repeated operator application."},
    {"id":"D004","statement":"Collatz is an application module, not the definition of the universal core."},
]

AXIOMS = [
    {"id":"A001","statement":"Exact integer arithmetic is used on the integer domain."},
    {"id":"A002","statement":"Finite computation does not by itself prove a universal theorem."},
]

def digest(payload):
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(raw).hexdigest()

def apply_operator(name, args, modulus=None):
    if name not in OPERATORS:
        raise ValueError("unknown operator")
    if len(args) != OPERATORS[name]["arity"]:
        raise ValueError("wrong arity")
    a = args[0]
    if name == "add": return a + args[1]
    if name == "subtract": return a - args[1]
    if name == "multiply": return a * args[1]
    if name == "divide_floor":
        if args[1] == 0: raise ValueError("division by zero")
        return a // args[1]
    if name == "modulo":
        if args[1] == 0: raise ValueError("modulo by zero")
        return a % args[1]
    if name == "add_mod":
        if modulus is None or modulus <= 0: raise ValueError("positive modulus required")
        return (a + args[1]) % modulus
    if name == "multiply_mod":
        if modulus is None or modulus <= 0: raise ValueError("positive modulus required")
        return (a * args[1]) % modulus
    if name == "collatz_step":
        if a <= 0: raise ValueError("positive integer required")
        return a // 2 if a % 2 == 0 else 3 * a + 1
    raise ValueError("operator not implemented")

def iterate(name, initial, steps, modulus=None):
    if steps < 0 or steps > 100000:
        raise ValueError("steps must be 0..100000")
    state = initial
    trajectory = [state]
    for _ in range(steps):
        state = apply_operator(name, [state] if OPERATORS[name]["arity"] == 1 else [state, 0], modulus)
        trajectory.append(state)
    payload = {"domain": OPERATORS[name]["domain"], "operator": name,
               "initial": initial, "steps": steps, "terminal": state,
               "trajectory": trajectory}
    return {**payload, "certificate": {
        "version": "1.1.0", "digest": digest(payload),
        "attestation": "reproducible_computation", "theorem_proved": False
    }}

class EvaluateRequest(BaseModel):
    n:int=Field(gt=0,le=10**18)
    max_steps:int=Field(default=10000,ge=1,le=1_000_000)

class SearchRequest(BaseModel):
    start:int=Field(gt=0,le=10**12)
    end:int=Field(gt=0,le=10**12)
    max_steps:int=Field(default=10000,ge=1,le=1_000_000)

HTML="""<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'>
<title>FICA–IGF-U v1.0.5</title><style>
body{font-family:system-ui;margin:0;background:#0b1020;color:#eef2ff}main{max-width:900px;margin:auto;padding:40px 20px}
.card{background:#151d33;padding:20px;margin:18px 0;border-radius:16px}input{display:block;width:100%;box-sizing:border-box;padding:10px;margin:8px 0;background:#0e1528;color:white;border:1px solid #394766;border-radius:8px}
button{padding:10px 16px;border:0;border-radius:8px;font-weight:700}pre{white-space:pre-wrap;background:#0e1528;padding:14px;border-radius:8px;overflow:auto}
</style></head><body><main><h1>FICA–IGF-U</h1><p>v1.0.5 · single-context deployment</p>
<div class='card'><h2>Evaluate</h2><input id='n' value='27' type='number'><input id='l' value='10000' type='number'>
<button onclick='go()'>Evaluate</button><pre id='o'></pre></div>
<div class='card'><h2>API</h2><p><a href='/docs'>/docs</a> · <a href='/api'>/api</a> · <a href='/api/health'>/api/health</a></p></div>
<script>async function go(){let r=await fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({n:+n.value,max_steps:+l.value})});o.textContent=JSON.stringify(await r.json(),null,2)}</script>
</main></body></html>"""

@app.get("/", response_class=HTMLResponse)
@app.head("/", include_in_schema=False)
@app.get("/app", response_class=HTMLResponse)
@app.head("/app", include_in_schema=False)
@app.get("/app/", response_class=HTMLResponse)
@app.head("/app/", include_in_schema=False)
@app.get("/apps", response_class=HTMLResponse)
@app.head("/apps", include_in_schema=False)
@app.get("/apps/", response_class=HTMLResponse)
@app.head("/apps/", include_in_schema=False)
def home():
    return HTML


OBJECT_TYPES = {
    "scalar": "A typed atomic value.",
    "set": "A finite explicitly represented collection.",
    "relation": "A finite collection of ordered pairs.",
    "function": "A finite deterministic mapping.",
    "sequence": "An ordered finite list.",
    "operator": "A registered transformation with domain and arity.",
    "proposition": "A machine-readable statement with verification status.",
    "experiment": "A reproducible computation record.",
}

def validate_object(obj):
    kind = obj.get("type")
    if kind not in OBJECT_TYPES:
        raise ValueError("unknown object type")
    if kind == "scalar":
        if "value" not in obj:
            raise ValueError("scalar requires value")
    elif kind == "set":
        if not isinstance(obj.get("elements"), list):
            raise ValueError("set requires elements list")
    elif kind == "sequence":
        if not isinstance(obj.get("elements"), list):
            raise ValueError("sequence requires elements list")
    elif kind == "relation":
        if not isinstance(obj.get("pairs"), list):
            raise ValueError("relation requires pairs list")
    elif kind == "function":
        if not isinstance(obj.get("mapping"), dict):
            raise ValueError("function requires mapping object")
    elif kind == "operator":
        if obj.get("name") not in OPERATORS:
            raise ValueError("function/operator name is not registered")
    elif kind == "proposition":
        if not isinstance(obj.get("statement"), str) or not obj["statement"].strip():
            raise ValueError("proposition requires statement")
    elif kind == "experiment":
        if "input" not in obj or "operator" not in obj:
            raise ValueError("experiment requires input and operator")
    return {
        "valid": True,
        "type": kind,
        "schema": OBJECT_TYPES[kind],
        "digest": digest(obj),
    }

@app.get("/api/objects/types")
def object_types():
    return {"version": app.version, "types": OBJECT_TYPES}

@app.post("/api/objects/validate")
def object_validate(req: dict):
    try:
        return validate_object(req)
    except ValueError as e:
        raise HTTPException(400, str(e))


INFERENCE_RULES = {
    "EQ_REFL": "x = x",
    "EQ_SYM": "x = y implies y = x",
    "EQ_TRANS": "x = y and y = z implies x = z",
    "DIVISIBLE": "a is divisible by b iff b != 0 and a mod b = 0",
}

def infer(step: dict) -> dict:
    rule = step.get("rule")
    if rule == "EQ_REFL":
        x = step.get("x")
        return {"valid": x is not None, "conclusion": {"left": x, "right": x}}
    if rule == "EQ_SYM":
        left, right = step.get("left"), step.get("right")
        if left is None or right is None:
            raise ValueError("EQ_SYM requires left and right")
        return {"valid": True, "conclusion": {"left": right, "right": left}}
    if rule == "EQ_TRANS":
        a, b, c = step.get("a"), step.get("b"), step.get("c")
        if a is None or b is None or c is None:
            raise ValueError("EQ_TRANS requires a, b, c")
        if b != step.get("middle"):
            raise ValueError("middle value must equal b")
        return {"valid": True, "conclusion": {"left": a, "right": c}}
    if rule == "DIVISIBLE":
        a, b = step.get("a"), step.get("b")
        if not isinstance(a, int) or not isinstance(b, int):
            raise ValueError("DIVISIBLE requires integer a and b")
        if b == 0:
            return {"valid": False, "reason": "zero divisor"}
        return {"valid": a % b == 0, "remainder": a % b}
    raise ValueError("unknown inference rule")

@app.get("/api/inference/rules")
def inference_rules():
    return {"version": app.version, "rules": INFERENCE_RULES}

@app.post("/api/inference/check")
def inference_check(req: dict):
    try:
        result = infer(req)
        return {"rule": req.get("rule"), **result, "theorem_proved": False}
    except ValueError as e:
        raise HTTPException(400, str(e))


def verify_proof_graph(graph: dict) -> dict:
    nodes = graph.get("nodes")
    if not isinstance(nodes, list) or not nodes:
        raise ValueError("proof graph requires non-empty nodes")
    by_id = {}
    for node in nodes:
        nid = node.get("id")
        if not isinstance(nid, str) or not nid:
            raise ValueError("each node requires a non-empty id")
        if nid in by_id:
            raise ValueError("duplicate node id")
        by_id[nid] = node

    verified = []
    for node in nodes:
        deps = node.get("depends_on", [])
        if not isinstance(deps, list):
            raise ValueError("depends_on must be a list")
        missing = [d for d in deps if d not in by_id]
        if missing:
            return {"status":"rejected","failed_node":node["id"],
                    "reason":"missing dependency","missing":missing,
                    "theorem_proved":False}
        rule = node.get("rule")
        if rule == "ASSUMPTION":
            ok = True
        else:
            ok = all(d in verified for d in deps)
            if rule in INFERENCE_RULES:
                try:
                    result = infer(node.get("inference", node))
                    ok = ok and bool(result.get("valid"))
                except ValueError as e:
                    return {"status":"rejected","failed_node":node["id"],
                            "reason":str(e),"theorem_proved":False}
            else:
                return {"status":"rejected","failed_node":node["id"],
                        "reason":"unknown proof rule","theorem_proved":False}
        if not ok:
            return {"status":"rejected","failed_node":node["id"],
                    "reason":"dependency or inference failed","theorem_proved":False}
        verified.append(node["id"])

    conclusion = graph.get("conclusion")
    return {
        "status":"verified_derivation",
        "verified_nodes":verified,
        "conclusion":conclusion,
        "theorem_proved":False,
        "certificate":{"version":app.version,"digest":digest(graph),
                       "attestation":"finite_proof_graph_verification"}
    }

@app.post("/api/proof/graph/verify")
def proof_graph_verify(req: dict):
    try:
        return verify_proof_graph(req)
    except ValueError as e:
        raise HTTPException(400, str(e))

@app.get("/api/proof/graph/schema")
def proof_graph_schema():
    return {
        "version":app.version,
        "node_fields":["id","rule","depends_on","inference"],
        "rules":["ASSUMPTION", *INFERENCE_RULES.keys()],
        "note":"Finite graph verification does not automatically establish a universal theorem."
    }


LOGIC_OBJECTS = {
    "assumption": "An explicitly declared premise.",
    "variable": "A named symbolic variable with an optional domain.",
    "quantifier": "A finite machine-readable universal or existential declaration.",
    "predicate": "A named Boolean-valued condition.",
    "theorem": "A proposition with explicit assumptions and proof status.",
}

QUANTIFIERS = {
    "forall": "For every element in a declared finite domain.",
    "exists": "There exists an element in a declared finite domain.",
}

def check_logic_object(obj):
    kind = obj.get("type")
    if kind not in LOGIC_OBJECTS:
        raise ValueError("unknown logic object type")
    if kind == "assumption":
        if not isinstance(obj.get("statement"), str) or not obj["statement"].strip():
            raise ValueError("assumption requires statement")
    elif kind == "variable":
        if not isinstance(obj.get("name"), str) or not obj["name"].strip():
            raise ValueError("variable requires name")
    elif kind == "quantifier":
        if obj.get("kind") not in QUANTIFIERS:
            raise ValueError("unknown quantifier")
        if not isinstance(obj.get("variable"), str):
            raise ValueError("quantifier requires variable")
        if not isinstance(obj.get("domain"), list):
            raise ValueError("v1.5 quantifiers require an explicit finite domain")
    elif kind == "predicate":
        if not isinstance(obj.get("name"), str) or not obj["name"].strip():
            raise ValueError("predicate requires name")
    elif kind == "theorem":
        if not isinstance(obj.get("statement"), str) or not obj["statement"].strip():
            raise ValueError("theorem requires statement")
        if not isinstance(obj.get("assumptions"), list):
            raise ValueError("theorem requires assumptions list")
    return {
        "valid": True,
        "type": kind,
        "schema": LOGIC_OBJECTS[kind],
        "digest": digest(obj),
        "theorem_proved": False,
    }

def check_finite_quantifier(q):
    if q.get("kind") not in QUANTIFIERS:
        raise ValueError("unknown quantifier")
    domain = q.get("domain")
    if not isinstance(domain, list) or not domain:
        raise ValueError("finite non-empty domain required")
    predicate = q.get("predicate")
    if not isinstance(predicate, dict):
        raise ValueError("predicate object required")
    # v1.5 supports explicit equality predicates only.
    if predicate.get("op") == "equals":
        value = predicate.get("value")
        return {
            "quantifier": q["kind"],
            "variable": q["variable"],
            "domain_size": len(domain),
            "satisfied": all(x == value for x in domain) if q["kind"] == "forall"
                         else any(x == value for x in domain),
        }
    raise ValueError("unsupported predicate; v1.5 supports equals")

@app.get("/api/logic/types")
def logic_types():
    return {"version": app.version, "types": LOGIC_OBJECTS}

@app.get("/api/logic/quantifiers")
def quantifier_types():
    return {"version": app.version, "quantifiers": QUANTIFIERS}

@app.post("/api/logic/validate")
def logic_validate(req: dict):
    try:
        return check_logic_object(req)
    except ValueError as e:
        raise HTTPException(400, str(e))

@app.post("/api/logic/quantifier/check")
def quantifier_check(req: dict):
    try:
        result = check_finite_quantifier(req)
        result["theorem_proved"] = False
        return result
    except ValueError as e:
        raise HTTPException(400, str(e))


THEOREM_STATUSES = {
    "proposed": "Statement has been declared but not verified.",
    "obligations_open": "Proof obligations exist and are not all discharged.",
    "verified_derivation": "All supplied finite obligations and proof steps passed verification.",
    "theorem_proved": "Reserved for a future kernel that discharges the complete formal theorem.",
}

def build_theorem(thm: dict) -> dict:
    if not isinstance(thm.get("id"), str) or not thm["id"]:
        raise ValueError("theorem requires id")
    if not isinstance(thm.get("statement"), str) or not thm["statement"].strip():
        raise ValueError("theorem requires statement")
    assumptions = thm.get("assumptions", [])
    obligations = thm.get("obligations", [])
    if not isinstance(assumptions, list) or not isinstance(obligations, list):
        raise ValueError("assumptions and obligations must be lists")
    return {
        "id": thm["id"],
        "statement": thm["statement"],
        "assumptions": assumptions,
        "obligations": obligations,
        "status": "obligations_open" if obligations else "proposed",
        "theorem_proved": False,
        "digest": digest(thm),
    }

def discharge_obligations(thm: dict) -> dict:
    record = build_theorem(thm)
    results = []
    for i, obligation in enumerate(record["obligations"], 1):
        if not isinstance(obligation, dict):
            return {"status":"rejected","failed_obligation":i,"reason":"obligation must be object","theorem_proved":False}
        kind = obligation.get("kind")
        if kind == "finite_quantifier":
            try:
                result = check_finite_quantifier(obligation["quantifier"])
                ok = bool(result.get("satisfied"))
            except ValueError as e:
                return {"status":"rejected","failed_obligation":i,"reason":str(e),"theorem_proved":False}
        elif kind == "inference":
            try:
                result = infer(obligation["inference"])
                ok = bool(result.get("valid"))
            except ValueError as e:
                return {"status":"rejected","failed_obligation":i,"reason":str(e),"theorem_proved":False}
        else:
            return {"status":"rejected","failed_obligation":i,"reason":"unknown obligation type","theorem_proved":False}
        results.append({"index":i,"kind":kind,"ok":ok,"result":result})
        if not ok:
            return {"status":"obligations_open","failed_obligation":i,
                    "obligations":results,"theorem_proved":False,
                    "theorem":record}
    return {
        "status":"verified_derivation",
        "theorem":record,
        "obligations":results,
        "theorem_proved":False,
        "certificate":{
            "version":app.version,
            "digest":digest({"theorem":record,"obligations":results}),
            "attestation":"finite_obligation_verification"
        }
    }

@app.get("/api/theorem/statuses")
def theorem_statuses():
    return {"version":app.version,"statuses":THEOREM_STATUSES}

@app.post("/api/theorem/validate")
def theorem_validate(req: dict):
    try:
        return build_theorem(req)
    except ValueError as e:
        raise HTTPException(400, str(e))

@app.post("/api/theorem/discharge")
def theorem_discharge(req: dict):
    try:
        return discharge_obligations(req)
    except ValueError as e:
        raise HTTPException(400, str(e))


ALGEBRA_RULES = {
    "ADD_ZERO": "x + 0 = x",
    "MUL_ONE": "x * 1 = x",
    "MUL_ZERO": "x * 0 = 0",
    "SUB_ZERO": "x - 0 = x",
    "DOUBLE_NEG": "-(-x) = x",
}

def normalize_algebra(expr: str) -> str:
    # Restricted, deterministic integer/symbolic rewrite engine.
    # This is intentionally not a full CAS.
    s = expr.replace(" ", "")
    if not s:
        raise ValueError("empty expression")
    changed = True
    while changed:
        changed = False
        replacements = [
            ("+0", ""),
            ("*1", ""),
            ("1*", ""),
            ("*0", "*0"),
            ("--", ""),
        ]
        for old, new in replacements:
            if old in s:
                ns = s.replace(old, new)
                if ns != s:
                    s, changed = ns, True
    if s.endswith("*0") or s.startswith("0*"):
        return "0"
    return s

def algebra_equivalent(left: str, right: str) -> dict:
    nl, nr = normalize_algebra(left), normalize_algebra(right)
    return {
        "left": left, "right": right,
        "left_normal_form": nl, "right_normal_form": nr,
        "equivalent": nl == nr,
        "ruleset": "restricted_v1.7",
        "theorem_proved": False,
    }

@app.get("/api/algebra/rules")
def algebra_rules():
    return {"version":app.version,"rules":ALGEBRA_RULES}

@app.post("/api/algebra/normalize")
def algebra_normalize(req: dict):
    try:
        expression = req["expression"]
        return {"expression":expression,
                "normal_form":normalize_algebra(expression),
                "theorem_proved":False}
    except (KeyError, ValueError) as e:
        raise HTTPException(400,str(e))

@app.post("/api/algebra/equivalent")
def algebra_equivalent_api(req: dict):
    try:
        return algebra_equivalent(req["left"], req["right"])
    except (KeyError, ValueError) as e:
        raise HTTPException(400,str(e))


def substitute(expr: str, bindings: dict) -> str:
    if not isinstance(expr, str) or not expr.strip():
        raise ValueError("expression required")
    if not isinstance(bindings, dict):
        raise ValueError("bindings must be an object")
    out = expr
    # Identifier-level substitution only; avoids replacing inside longer identifiers.
    import re
    for name, value in bindings.items():
        if not isinstance(name, str) or not name.isidentifier():
            raise ValueError("binding names must be identifiers")
        if not isinstance(value, (int, str)):
            raise ValueError("binding values must be integers or strings")
        out = re.sub(rf"\b{re.escape(name)}\b", str(value), out)
    return out

def binding_record(variable: str, value):
    if not isinstance(variable, str) or not variable.isidentifier():
        raise ValueError("variable must be an identifier")
    if not isinstance(value, (int, str)):
        raise ValueError("value must be integer or string")
    return {"variable":variable,"value":value,"valid":True,"theorem_proved":False}

@app.get("/api/binding/schema")
def binding_schema():
    return {
        "version":app.version,
        "binding":{
            "variable":"identifier",
            "value":"integer|string",
            "scope":"explicit request"
        },
        "capture_avoidance":"identifier-boundary substitution only"
    }

@app.post("/api/binding/validate")
def binding_validate(req: dict):
    try:
        return binding_record(req["variable"], req["value"])
    except (KeyError, ValueError) as e:
        raise HTTPException(400,str(e))

@app.post("/api/binding/substitute")
def binding_substitute(req: dict):
    try:
        result = substitute(req["expression"], req["bindings"])
        return {
            "expression":req["expression"],
            "bindings":req["bindings"],
            "substituted":result,
            "normal_form":normalize_algebra(result),
            "theorem_proved":False
        }
    except (KeyError, ValueError) as e:
        raise HTTPException(400,str(e))


FUNCTIONS = {
    "identity": {"domain":"integer","codomain":"integer","arity":1},
    "double": {"domain":"integer","codomain":"integer","arity":1},
    "square": {"domain":"integer","codomain":"integer","arity":1},
    "collatz_step": {"domain":"integer","codomain":"integer","arity":1},
}

def apply_function(name, x):
    if name == "identity": return x
    if name == "double": return 2*x
    if name == "square": return x*x
    if name == "collatz_step":
        if x <= 0: raise ValueError("positive integer required")
        return x//2 if x%2==0 else 3*x+1
    raise ValueError("unknown function")

def compose_functions(first, second):
    if first not in FUNCTIONS or second not in FUNCTIONS:
        raise ValueError("unknown function")
    return {
        "type":"composition",
        "expression":f"{second}∘{first}",
        "domain":FUNCTIONS[first]["domain"],
        "codomain":FUNCTIONS[second]["codomain"],
        "definition":f"x ↦ {second}({first}(x))",
    }

@app.get("/api/functions")
def functions():
    return {"version":app.version,"functions":FUNCTIONS}

@app.post("/api/function/apply")
def function_apply(req: dict):
    try:
        name=req["function"]; x=req["input"]
        if not isinstance(x,int): raise ValueError("input must be integer")
        return {"function":name,"input":x,"output":apply_function(name,x),
                "theorem_proved":False}
    except (KeyError,ValueError) as e:
        raise HTTPException(400,str(e))

@app.post("/api/function/compose")
def function_compose(req: dict):
    try:
        c=compose_functions(req["first"],req["second"])
        if "input" in req:
            x=req["input"]
            y=apply_function(req["second"],apply_function(req["first"],x))
            c["input"]=x; c["output"]=y
        c["theorem_proved"]=False
        return c
    except (KeyError,ValueError) as e:
        raise HTTPException(400,str(e))


KERNEL_VERSION = "2.0.0"

# v3.1: Collatz is an application module, never the universal core.
UNIVERSAL_OPERATORS = {
    "add": {"domain":"integer", "codomain":"integer", "arity":2, "family":"arithmetic"},
    "subtract": {"domain":"integer", "codomain":"integer", "arity":2, "family":"arithmetic"},
    "multiply": {"domain":"integer", "codomain":"integer", "arity":2, "family":"arithmetic"},
    "divide_floor": {"domain":"integer", "codomain":"integer", "arity":2, "family":"arithmetic"},
    "modulo": {"domain":"integer", "codomain":"integer", "arity":2, "family":"arithmetic"},
    "add_mod": {"domain":"modular", "codomain":"modular", "arity":3, "family":"modular"},
    "multiply_mod": {"domain":"modular", "codomain":"modular", "arity":3, "family":"modular"},
    "identity": {"domain":"integer", "codomain":"integer", "arity":1, "family":"function"},
    "negate": {"domain":"integer", "codomain":"integer", "arity":1, "family":"function"},
    "double": {"domain":"integer", "codomain":"integer", "arity":1, "family":"function"},
    "square": {"domain":"integer", "codomain":"integer", "arity":1, "family":"function"},
}

APPLICATION_MODULES = {
    "collatz": {
        "status":"application",
        "description":"A registered research/example module using integer iteration.",
        "operator":"collatz_step",
    }
}

def apply_universal_operator(name, args):
    spec = UNIVERSAL_OPERATORS.get(name)
    if spec is None:
        raise ValueError("unknown universal operator")
    if not isinstance(args, list) or len(args) != spec["arity"]:
        raise ValueError("wrong arity")
    if name == "add": return args[0] + args[1]
    if name == "subtract": return args[0] - args[1]
    if name == "multiply": return args[0] * args[1]
    if name == "divide_floor":
        if args[1] == 0: raise ValueError("division by zero")
        return args[0] // args[1]
    if name == "modulo":
        if args[1] == 0: raise ValueError("modulo by zero")
        return args[0] % args[1]
    if name == "add_mod":
        if args[2] <= 0: raise ValueError("positive modulus required")
        return (args[0] + args[1]) % args[2]
    if name == "multiply_mod":
        if args[2] <= 0: raise ValueError("positive modulus required")
        return (args[0] * args[1]) % args[2]
    if name == "identity": return args[0]
    if name == "negate": return -args[0]
    if name == "double": return 2 * args[0]
    if name == "square": return args[0] * args[0]
    raise ValueError("operator implementation missing")

@app.get("/api/operators/universal")
def universal_operators():
    return {
        "version": app.version,
        "operators": UNIVERSAL_OPERATORS,
        "application_modules": APPLICATION_MODULES,
        "principle": "Collatz is an application, not the platform core.",
    }

@app.post("/api/operators/apply")
def universal_operator_apply(req: dict):
    try:
        result = apply_universal_operator(req["operator"], req["args"])
        payload = {"operator":req["operator"], "args":req["args"], "result":result}
        return {**payload, "certificate":make_kernel_certificate(payload)}
    except (KeyError, ValueError) as e:
        raise HTTPException(400, str(e))



UNIFIED_SCHEMA = {
    "state": ["id","domain","value"],
    "expression": ["operator","arguments"],
    "function": ["name","domain","codomain","definition"],
    "relation": ["left","relation","right"],
    "proposition": ["statement","assumptions"],
    "derivation": ["premises","steps","conclusion"],
    "certificate": ["digest","attestation","status"],
}

def canonicalize(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)

def kernel_digest(value):
    return hashlib.sha256(canonicalize(value).encode()).hexdigest()

def validate_unified_object(obj):
    if not isinstance(obj, dict):
        raise ValueError("unified object must be an object")
    kind=obj.get("kind")
    if kind not in UNIFIED_SCHEMA:
        raise ValueError("unknown unified object kind")
    required=UNIFIED_SCHEMA[kind]
    missing=[k for k in required if k not in obj]
    if missing:
        raise ValueError("missing fields: " + ",".join(missing))
    return {
        "valid":True,
        "kind":kind,
        "schema":required,
        "digest":kernel_digest(obj),
        "kernel_version":KERNEL_VERSION,
    }

def make_kernel_certificate(payload, status="verified_computation"):
    return {
        "kernel_version":KERNEL_VERSION,
        "digest":kernel_digest(payload),
        "attestation":"unified_kernel",
        "status":status,
        "theorem_proved":False,
    }

@app.get("/api/kernel")
def kernel_info():
    return {
        "name":"FICA–IGF-U Unified Mathematical Kernel",
        "version":KERNEL_VERSION,
        "status":"online",
        "principle":"one common representation for mathematical objects and derivations",
        "schema":UNIFIED_SCHEMA,
    }

@app.post("/api/kernel/validate")
def kernel_validate(req: dict):
    try:
        return validate_unified_object(req)
    except ValueError as e:
        raise HTTPException(400,str(e))

@app.post("/api/kernel/certificate")
def kernel_certificate(req: dict):
    try:
        validated=validate_unified_object(req)
        return {
            **validated,
            "certificate":make_kernel_certificate(req)
        }
    except ValueError as e:
        raise HTTPException(400,str(e))


SCIENCE_DOMAINS = {
    "mathematics": {"objects":["number","set","function","relation","proof"],"methods":["deduction","formal_verification"]},
    "physics": {"objects":["state","observable","parameter","dynamical_system"],"methods":["modeling","simulation","dimensional_analysis"]},
    "computer_science": {"objects":["algorithm","program","state","graph"],"methods":["execution","complexity_analysis","verification"]},
    "statistics": {"objects":["sample","distribution","parameter","hypothesis"],"methods":["estimation","inference","simulation"]},
    "information_theory": {"objects":["symbol","message","channel","code"],"methods":["entropy","coding","channel_analysis"]},
    "chemistry": {"objects":["species","reaction","concentration","equilibrium"],"methods":["reaction_modeling","balance_constraints"]},
    "biology": {"objects":["organism","population","network","trait"],"methods":["population_modeling","network_analysis"]},
    "engineering": {"objects":["system","component","constraint","measurement"],"methods":["simulation","optimization","verification"]},
    "economics": {"objects":["agent","market","utility","resource"],"methods":["modeling","optimization","statistical_analysis"]},
    "linguistics": {"objects":["token","grammar","meaning","discourse"],"methods":["formal_analysis","corpus_analysis"]},
    "philosophy": {"objects":["concept","proposition","argument","premise"],"methods":["argument_analysis","conceptual_analysis"]},
    "social_science": {"objects":["agent","group","observation","network"],"methods":["statistical_analysis","causal_modeling"]},
}

CROSS_DOMAIN_RELATIONS = [
    {"id":"R001","name":"measurement","from":"physics","to":"mathematics"},
    {"id":"R002","name":"simulation","from":"mathematics","to":"physics"},
    {"id":"R003","name":"algorithmic_model","from":"mathematics","to":"computer_science"},
    {"id":"R004","name":"statistical_observation","from":"experiment","to":"statistics"},
    {"id":"R005","name":"formal_argument","from":"philosophy","to":"mathematics"},
]

@app.get("/api/science/domains")
def science_domains():
    return {"version":app.version,"domains":SCIENCE_DOMAINS}

@app.get("/api/science/relations")
def science_relations():
    return {"version":app.version,"relations":CROSS_DOMAIN_RELATIONS}

@app.post("/api/science/model/validate")
def science_model_validate(req: dict):
    domain=req.get("domain")
    if domain not in SCIENCE_DOMAINS:
        raise HTTPException(400,"unknown science domain")
    model=req.get("model")
    if not isinstance(model,dict):
        raise HTTPException(400,"model must be an object")
    payload={"domain":domain,"model":model}
    return {
        "valid":True,
        "domain":domain,
        "model":model,
        "digest":kernel_digest(payload),
        "status":"model_schema_validated",
        "scientific_truth_proved":False,
    }


CROSS_DOMAIN_NODE_TYPES = {
    "assumption":"A domain-scoped premise.",
    "measurement":"An observed or supplied measurement.",
    "equation":"A mathematical relation used by a model.",
    "algorithm":"A computational transformation.",
    "hypothesis":"A testable domain-scoped proposition.",
    "result":"An output produced by a computation or analysis.",
    "evidence":"A recorded support item with provenance metadata.",
}

def validate_cross_domain_graph(graph):
    if not isinstance(graph,dict): raise ValueError("graph must be an object")
    nodes=graph.get("nodes")
    edges=graph.get("edges",[])
    if not isinstance(nodes,list) or not nodes: raise ValueError("nodes must be non-empty list")
    if not isinstance(edges,list): raise ValueError("edges must be a list")
    ids=set()
    normalized=[]
    for n in nodes:
        if not isinstance(n,dict) or not isinstance(n.get("id"),str):
            raise ValueError("each node requires id")
        if n["id"] in ids: raise ValueError("duplicate node id")
        if n.get("domain") not in SCIENCE_DOMAINS:
            raise ValueError("node has unknown science domain")
        if n.get("type") not in CROSS_DOMAIN_NODE_TYPES:
            raise ValueError("node has unknown type")
        ids.add(n["id"]); normalized.append(n)
    for e in edges:
        if not isinstance(e,dict) or e.get("source") not in ids or e.get("target") not in ids:
            raise ValueError("edge references unknown node")
        if not isinstance(e.get("relation"),str) or not e["relation"]:
            raise ValueError("edge requires relation")
    payload={"nodes":normalized,"edges":edges}
    return {
        "valid":True,
        "node_count":len(normalized),
        "edge_count":len(edges),
        "domains":sorted({n["domain"] for n in normalized}),
        "digest":kernel_digest(payload),
        "status":"cross_domain_graph_validated",
        "scientific_truth_proved":False,
    }

@app.get("/api/science/graph/schema")
def science_graph_schema():
    return {"version":app.version,"node_types":CROSS_DOMAIN_NODE_TYPES,
            "required_node_fields":["id","domain","type"],
            "required_edge_fields":["source","target","relation"]}

@app.post("/api/science/graph/validate")
def science_graph_validate(req: dict):
    try:
        return validate_cross_domain_graph(req)
    except ValueError as e:
        raise HTTPException(400,str(e))


PROVENANCE_TYPES = {
    "source":"Origin record for an input or claim.",
    "dataset":"Named data collection with version metadata.",
    "measurement":"Observed value with acquisition metadata.",
    "transformation":"A declared computational/model transformation.",
    "result":"Output produced from recorded inputs and transformations.",
    "claim":"A statement supported by recorded evidence.",
}

def validate_provenance(record):
    if not isinstance(record,dict): raise ValueError("record must be object")
    rid=record.get("id")
    kind=record.get("type")
    if not isinstance(rid,str) or not rid: raise ValueError("record requires id")
    if kind not in PROVENANCE_TYPES: raise ValueError("unknown provenance type")
    parents=record.get("derived_from",[])
    if not isinstance(parents,list): raise ValueError("derived_from must be list")
    return {
        "valid":True,
        "id":rid,
        "type":kind,
        "derived_from":parents,
        "metadata":record.get("metadata",{}),
        "digest":kernel_digest(record),
        "status":"provenance_record_validated",
        "truth_status":"not_established_by_provenance",
    }

def validate_provenance_chain(chain):
    if not isinstance(chain,list) or not chain: raise ValueError("chain must be non-empty list")
    ids=set()
    records={}
    for r in chain:
        v=validate_provenance(r)
        if v["id"] in ids: raise ValueError("duplicate provenance id")
        ids.add(v["id"]); records[v["id"]]=v
    broken=[]
    for v in records.values():
        for parent in v["derived_from"]:
            if parent not in records: broken.append((v["id"],parent))
    if broken:
        return {"valid":False,"broken_links":broken,"status":"provenance_chain_broken"}
    return {
        "valid":True,
        "record_count":len(records),
        "ordered_ids":[r["id"] for r in chain],
        "digest":kernel_digest(chain),
        "status":"provenance_chain_validated",
        "truth_status":"not_established_by_provenance",
    }

@app.get("/api/provenance/types")
def provenance_types():
    return {"version":app.version,"types":PROVENANCE_TYPES}

@app.post("/api/provenance/validate")
def provenance_validate(req:dict):
    try: return validate_provenance(req)
    except ValueError as e: raise HTTPException(400,str(e))

@app.post("/api/provenance/chain/validate")
def provenance_chain_validate(req:dict):
    try: return validate_provenance_chain(req["chain"])
    except (KeyError,ValueError) as e: raise HTTPException(400,str(e))


# ---------------------------------------------------------------------------
# v2.4/v2.5/v3.0 final integrated measurement, experiment and audit layer
# ---------------------------------------------------------------------------

UNITS = {
    "1": {},
    "m": {"L": 1},
    "s": {"T": 1},
    "kg": {"M": 1},
    "K": {"Theta": 1},
    "A": {"I": 1},
    "mol": {"N": 1},
}

def unit_signature(unit: str) -> dict:
    if unit not in UNITS:
        raise ValueError("unknown base unit")
    return dict(UNITS[unit])

def combine_units(a: dict, b: dict, sign: int = 1) -> dict:
    out = dict(a)
    for k, v in b.items():
        out[k] = out.get(k, 0) + sign * v
        if out[k] == 0:
            del out[k]
    return out

def unit_product(u1: str, u2: str) -> dict:
    return combine_units(unit_signature(u1), unit_signature(u2), 1)

def unit_division(u1: str, u2: str) -> dict:
    return combine_units(unit_signature(u1), unit_signature(u2), -1)

def validate_measurement(req: dict) -> dict:
    if not isinstance(req.get("value"), (int, float)):
        raise ValueError("measurement value must be numeric")
    unit = req.get("unit")
    unit_signature(unit)
    uncertainty = req.get("uncertainty", 0)
    if not isinstance(uncertainty, (int, float)) or uncertainty < 0:
        raise ValueError("uncertainty must be non-negative")
    if uncertainty > abs(req["value"]) and req["value"] != 0:
        relative = None
    else:
        relative = uncertainty / abs(req["value"]) if req["value"] != 0 else None
    payload = {
        "value": req["value"],
        "unit": unit,
        "uncertainty": uncertainty,
        "relative_uncertainty": relative,
        "exact": uncertainty == 0,
        "unit_signature": unit_signature(unit),
    }
    return {
        "valid": True,
        "measurement": payload,
        "digest": kernel_digest(payload),
        "status": "measurement_validated",
        "empirical_truth_proved": False,
    }

def propagate_add(m1: dict, m2: dict) -> dict:
    if m1["unit"] != m2["unit"]:
        raise ValueError("addition requires identical units in v3.0")
    value = m1["value"] + m2["value"]
    uncertainty = (m1["uncertainty"]**2 + m2["uncertainty"]**2) ** 0.5
    return {"value": value, "unit": m1["unit"], "uncertainty": uncertainty,
            "method": "root_sum_square_independent"}

def validate_experiment(exp: dict) -> dict:
    if not isinstance(exp.get("id"), str) or not exp["id"]:
        raise ValueError("experiment requires id")
    if not isinstance(exp.get("inputs"), list):
        raise ValueError("experiment inputs must be list")
    for item in exp["inputs"]:
        validate_measurement(item)
    result = exp.get("result")
    if result is not None:
        validate_measurement(result)
    payload = {
        "id": exp["id"],
        "inputs": exp["inputs"],
        "method": exp.get("method", ""),
        "result": result,
    }
    return {
        "valid": True,
        "id": exp["id"],
        "input_count": len(exp["inputs"]),
        "has_result": result is not None,
        "digest": kernel_digest(payload),
        "status": "experiment_schema_validated",
        "empirical_truth_proved": False,
    }

@app.get("/api/measurement/units")
def measurement_units():
    return {"version": app.version, "units": UNITS}

@app.post("/api/measurement/validate")
def measurement_validate(req: dict):
    try:
        return validate_measurement(req)
    except ValueError as e:
        raise HTTPException(400, str(e))

@app.post("/api/measurement/add")
def measurement_add(req: dict):
    try:
        a = validate_measurement(req["a"])["measurement"]
        b = validate_measurement(req["b"])["measurement"]
        result = propagate_add(a, b)
        return {
            "valid": True,
            "result": result,
            "digest": kernel_digest(result),
            "status": "uncertainty_propagated",
            "empirical_truth_proved": False,
        }
    except (KeyError, ValueError) as e:
        raise HTTPException(400, str(e))

@app.post("/api/experiment/validate")
def experiment_validate(req: dict):
    try:
        return validate_experiment(req)
    except ValueError as e:
        raise HTTPException(400, str(e))

@app.get("/api/audit/status")
def audit_status():
    return {
        "version": app.version,
        "architecture": "unified_multidomain_research_kernel",
        "layers": [
            "formal_objects",
            "inference",
            "proof_graph",
            "theorem_obligations",
            "algebra_rewrite",
            "variable_binding",
            "functions_composition",
            "science_domains",
            "cross_domain_graph",
            "provenance",
            "measurement_uncertainty",
            "experiment_validation",
        ],
        "status": "operational_prototype",
        "core_is_domain_neutral": True,
        "unrestricted_theorem_proving": False,
        "empirical_validation": False,
    }

@app.get("/api/final")
def final_manifest():
    return {
        "name": "FICA–IGF-U",
        "version": "4.0.0",
        "release": "all-domains research framework",
        "status": "operational_prototype",
        "core_is_domain_neutral": True,
        "scope": [
            "mathematics", "physics", "computer_science", "statistics",
            "information_theory", "chemistry", "biology", "engineering",
            "economics", "linguistics", "philosophy", "social_science"
        ],
        "core_capabilities": [
            "unified mathematical objects",
            "registered operators and functions",
            "formal inference",
            "proof graphs",
            "theorem obligations",
            "algebraic rewriting",
            "variable binding",
            "cross-domain model graphs",
            "provenance chains",
            "measurements and uncertainty",
            "experiment schema validation",
            "deterministic certificates",
        ],
        "limitations": [
            "not an unrestricted theorem prover",
            "not a substitute for empirical validation",
            "scientific model validation is structural, not truth certification",
            "finite computations do not establish universal claims",
        ],
    }


# v4.0 — domain-complete research framework based on a broad R&D field taxonomy.
# This is a unified framework with domain-specific primitive engines, not a claim
# that every subfield has been fully automated.

ALL_SCIENCE_DOMAINS = {
    "mathematics": ["pure_mathematics","applied_mathematics","statistics","probability"],
    "computer_information_sciences": ["algorithms","software","ai","data_science","information_theory","cybernetics"],
    "physical_sciences": ["physics","astronomy","space_science","optics","acoustics"],
    "chemical_sciences": ["chemistry","physical_chemistry","analytical_chemistry","materials_chemistry"],
    "earth_environmental_sciences": ["geology","geophysics","meteorology","climatology","oceanography","ecology","environmental_science"],
    "biological_sciences": ["cell_biology","molecular_biology","genetics","microbiology","botany","zoology","evolution","neuroscience"],
    "engineering_technology": ["civil","mechanical","electrical","electronics","chemical_engineering","materials","aerospace","industrial","environmental","nanotechnology","biotechnology"],
    "medical_health_sciences": ["basic_medicine","clinical_medicine","dentistry","nursing","public_health","epidemiology","pharmacology","medical_biotechnology"],
    "agricultural_veterinary_sciences": ["agriculture","forestry","fisheries","animal_science","veterinary_science","food_science"],
    "social_sciences": ["psychology","economics","education","sociology","law","political_science","human_geography","media_communications","management","anthropology"],
    "humanities_arts": ["history","archaeology","languages","literature","philosophy","ethics","religion","arts","music","performing_arts","cultural_studies"],
}

DOMAIN_PRIMITIVES = {
    "mathematics": ["symbolic_expression","equation","set","function","proof","optimization"],
    "computer_information_sciences": ["program","algorithm","graph","automaton","dataset","model"],
    "physical_sciences": ["physical_quantity","field","particle","state","dynamical_system","measurement"],
    "chemical_sciences": ["species","reaction","concentration","thermodynamic_state","equilibrium","spectrum"],
    "earth_environmental_sciences": ["location","layer","sample","climate_state","ecosystem","geophysical_field"],
    "biological_sciences": ["organism","cell","gene","population","trait","biological_network"],
    "engineering_technology": ["component","system","constraint","load","signal","control_loop"],
    "medical_health_sciences": ["patient_observation","biomarker","intervention","cohort","outcome","clinical_measurement"],
    "agricultural_veterinary_sciences": ["crop","animal","soil","field_trial","yield","pathogen"],
    "social_sciences": ["agent","population","survey","institution","network","behavioral_observation"],
    "humanities_arts": ["text","artifact","document","concept","argument","cultural_object"],
}

def domain_registry():
    return {
        "taxonomy_basis":"OECD Frascati-style broad R&D fields",
        "domains":ALL_SCIENCE_DOMAINS,
        "primitives":DOMAIN_PRIMITIVES,
        "status":"registered_and_api_exposed",
        "coverage_note":"Registry and primitive operations are complete at framework level; specialized research methods remain domain-specific.",
    }

def run_domain_primitive(domain, operation, payload):
    if domain not in ALL_SCIENCE_DOMAINS:
        raise ValueError("unknown domain")
    if operation == "describe":
        return {"domain":domain,"primitives":DOMAIN_PRIMITIVES[domain]}
    if operation == "validate_object":
        if not isinstance(payload, dict):
            raise ValueError("payload must be object")
        kind = payload.get("type")
        if kind not in DOMAIN_PRIMITIVES[domain]:
            raise ValueError("object type not registered for domain")
        return {"valid":True,"domain":domain,"type":kind,
                "digest":kernel_digest(payload)}
    if operation == "summarize":
        if not isinstance(payload, dict):
            raise ValueError("payload must be object")
        return {"domain":domain,"keys":sorted(payload.keys()),
                "digest":kernel_digest(payload)}
    raise ValueError("unsupported domain operation")

@app.get("/api/science/all-domains")
def all_domains():
    return domain_registry()

@app.post("/api/science/domain/operate")
def domain_operate(req: dict):
    try:
        result = run_domain_primitive(req["domain"], req["operation"], req.get("payload", {}))
        return {"result":result, "status":"domain_operation_verified"}
    except (KeyError, ValueError) as e:
        raise HTTPException(400, str(e))

@app.get("/api/science/coverage")
def science_coverage():
    return {
        "version":"4.0.0",
        "domains":len(ALL_SCIENCE_DOMAINS),
        "subfields":sum(len(v) for v in ALL_SCIENCE_DOMAINS.values()),
        "domain_engines":{d:"framework+primitive_engine" for d in ALL_SCIENCE_DOMAINS},
        "fully_automated_every_subfield":False,
        "reason":"No generic software system can honestly claim complete automation of every scientific subfield; v4.0 provides a common executable framework and extensible primitives.",
    }

@app.get("/api")
def api_root():
    return {"name":"FICA–IGF-U","version":app.version,"status":"online","release":"3.0.0","kernel_version":KERNEL_VERSION,
            "architecture":"unified_multidomain_research_kernel","science_domains":list(SCIENCE_DOMAINS),"endpoints":["/api/health","/api/registry","/api/domains","/api/operators","/api/operator/apply","/api/iterate","/api/objects/types","/api/objects/validate","/api/logic/types","/api/logic/quantifiers","/api/logic/validate","/api/logic/quantifier/check","/api/inference/rules","/api/inference/check","/api/proof/graph/schema","/api/proof/graph/verify","/api/theorem/statuses","/api/theorem/validate","/api/theorem/discharge","/api/algebra/rules","/api/algebra/normalize","/api/algebra/equivalent","/api/binding/schema","/api/functions","/api/function/apply","/api/function/compose","/api/binding/validate","/api/binding/substitute","/api/evaluate","/api/search","/docs"]}

@app.get("/api/health")
@app.head("/api/health", include_in_schema=False)
def health(): return {"status":"ok","version":app.version}

@app.get("/healthz", include_in_schema=False)
@app.head("/healthz", include_in_schema=False)
def healthz():
    return {"status":"ok"}


@app.get("/api/registry")
def registry():
    return {"version": app.version, "domains": DOMAINS,
            "operators": OPERATORS, "definitions": DEFINITIONS, "axioms": AXIOMS}

@app.get("/api/domains")
def domains():
    return {"version": app.version, "domains": DOMAINS}

@app.get("/api/operators")
def operators():
    return {"version": app.version, "operators": OPERATORS}

@app.post("/api/operator/apply")
def operator_apply(req: dict):
    try:
        return {"operator": req["operator"],
                "result": apply_operator(req["operator"], req["args"], req.get("modulus")),
                "theorem_proved": False}
    except (KeyError, ValueError, IndexError) as e:
        raise HTTPException(400, str(e))

@app.post("/api/iterate")
def api_iterate(req: dict):
    try:
        return iterate(req["operator"], req["initial"], req.get("steps", 10), req.get("modulus"))
    except (KeyError, ValueError, IndexError) as e:
        raise HTTPException(400, str(e))

@app.post("/api/evaluate")
def api_evaluate(req:EvaluateRequest):
    try:
        return iterate("collatz_step", req.n, req.max_steps)
    except ValueError as e:
        raise HTTPException(400,str(e))

@app.post("/api/search")
def api_search(req:SearchRequest):
    if req.end<req.start or req.end-req.start>5000:
        raise HTTPException(400,"invalid bounded range")
    rows=[]
    for n in range(req.start,req.end+1):
        r=evaluate(n,req.max_steps)
        rows.append({"n":n,"steps":r["steps"],"terminal":r["terminal"],"reached_1":r["terminal"]==1})
    bad=[x for x in rows if not x["reached_1"]]
    return {"tested":len(rows),"counterexamples":bad,
            "status":"no_counterexample_in_bounded_range" if not bad else "counterexample_found"}

@app.get("/api/tests")
def tests():
    return {"status":"production_test_manifest_not_embedded",
            "note":"Tests run in CI; production image intentionally has no tests directory."}

@app.get("/api/tests/status")
def tests_status():
    return {"status":"ci_managed","version":app.version}
