services:
  - type: web
    name: fica-igfu
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeployTrigger: checksPass
    maxShutdownDelaySeconds: 30
